GET http://localhost:3001/todos

###############

POST http://localhost:3001/todo/new
Content-Type: application/application/json

{
    "text" : "get the milk"
}

################

DELETE http://localhost:3001/todo/delete/64226525c391410c816d574d

#################

PUT http://localhost:3001/todo/complete/642204492c5e980850e01ef9


